//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atestados.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluacion
    {
        public int EvaluacionID { get; set; }
        public int AtestadoID { get; set; }
        public int RubricaID { get; set; }
        public int Puntaje { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Atestado Atestado { get; set; }
        public virtual Rubrica Rubrica { get; set; }
    }
}
