//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atestados.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisito
    {
        public int RequisitoID { get; set; }
        public string Descripcion { get; set; }
        public int RubricaID { get; set; }
    
        public virtual Rubrica Rubrica { get; set; }
    }
}
