//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atestados.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubrica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rubrica()
        {
            this.Evaluacion = new HashSet<Evaluacion>();
            this.Requisito = new HashSet<Requisito>();
            this.SeleccionPuntaje = new HashSet<SeleccionPuntaje>();
        }
    
        public int RubricaID { get; set; }
        public int TipoPuntajeID { get; set; }
        public Nullable<double> ValorPuntaje { get; set; }
        public string DescripcionPuntaje { get; set; }
        public System.DateTime Fecha { get; set; }
        public int RubroID { get; set; }
        public Nullable<int> PuntajeTiempoID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluacion> Evaluacion { get; set; }
        public virtual PuntajeTiempo PuntajeTiempo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisito> Requisito { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual TipoPuntaje TipoPuntaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeleccionPuntaje> SeleccionPuntaje { get; set; }
    }
}
