//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atestados.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubrica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rubrica()
        {
            this.Evaluacion = new HashSet<Evaluacion>();
            this.Requisito = new HashSet<Requisito>();
            this.SeleccionPuntaje = new HashSet<SeleccionPuntaje>();
        }
    
        public int RubricaID { get; set; }
        public int TipoPuntajeID { get; set; }
        public Nullable<double> ValorPuntaje { get; set; }
        public string DescripcionPuntaje { get; set; }
        public bool EsManual { get; set; }
        public System.DateTime Fecha { get; set; }
        public int RubroID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluacion> Evaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisito> Requisito { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual TipoPuntaje TipoPuntaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeleccionPuntaje> SeleccionPuntaje { get; set; }
    }
}
